version: "3.9"
services:
  apiserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "gunicorn -b 127.0.0.1:8000 web_app.wsgi:app"
    ports:
      - "8000:8000"
    mem_limit: 512m  # Увеличение лимита оперативной памяти для контейнера
    mem_reservation: 256m  # Резервирование оперативной памяти для контейнера
    cpus: 2
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "Paul"
      POSTGRES_PASSWORD: "123qwe"
      POSTGRES_DB: "metoResource"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Paul -d metoResource"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: