version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=metoResource
      - POSTGRES_USER=Paul
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    
  db:
    image: postgres
    environment:
      - POSTGRES_DB=metoResource
      - POSTGRES_USER=Paul
      - POSTGRES_PASSWORD=123qwe
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Paul -d metoResource"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.reactapp
    ports:
      - "3000:3000"